[package]
name = "ublog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
lazy_static = "1.4.0"
thiserror = "1.0.37"
toml = "0.5.9"
edit = "0.1.4"
expanduser = "1.2.2"
